<div class="int">

	<h2>Professor Shyguy</h2>
	
	<div class="scroll">

		<img src="assets/screens/shyguyscreen.png" alt="" />
			
			<div class="textint">
				<h3>The Request:</h3>
				<p>
					Website redesign for chip-pop darling and poor-nerd's Justin Timberlake, Professor Shyguy.<br />
					Easy navigation, so fans can find his music was paramount, as was the ability to easily make updates from the road.
				</p>
				<h3>The Project:</h3>
				<p>
					Professor Shyguy has a distinctive, fun sound, and his album art reflects that.<br />
					The cover image from his recent album <a href="http://professorshyguy.bandcamp.com/album/rated-heart">"Rated Heart"</a> was a natural centerpiece. The accent: a 16-bit pixel motif, not unlike the Professor's music. His emblematic pixel heart falls behind the main menu links and background pixels re-arrange themselves to display content.
				</p>
				<p>
					Content management is driven by familliar stalwart <a href="http://wordpress.org">Wordpress,</a> with editing via iOS app capability. Music and merchandise data is delivered by platforms <a href="http://bandcamp.com">Bandcamp</a> and <a href="http://storeenvy.com">StoreEnvy.</a>
				</p>
				<h3>Geeky Trivia:</h3>
					<ul>
						<li>
							There are only three images in use for this design. The album art, the pixel heart, and the pixel background. Everything else is either embedded fonts or generated by code.
						</li>
						<li>
							Professor Shyguy's music is <i>really good</i> and <a href="http://professorshyguy.com">worth checking out.</a>
						</li>
					</ul>
				<br />
				<h3>See it in Action:</h3>
				<p>
					<a href="http://professorshyguy.com">Professor Shyguy Dot Com</a>						
				</p>
				
			<?php include("../assets/back.php"); ?>
			
			</div><!-- /textint -->
			
	</div><!-- /scroll -->

	<!-- Close Button -->	
		<?php include("../assets/close.php"); ?>
	
</div><!-- /int -->